layout_spectrum: 0.15623083640821278
typography_spectrum: 0.847526885336265
color:
  brandStrength: 0.8091226618271321
  lightness: 0.5324107713531703
  saturation: 0.5689186716917902
  rhythmicContrast: 0.5701794498600066
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
content_rating:
  adult: false
author:
  name: Morten
  email: mortenprads@gmail.com
  url: 'http://mopra.dk'
logo: null
name: mopradk
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3a4a85dd-26fd-4fb4-b51b-b6c84258b59e.png
title: mopradk
description: Digital Konceptudvikler
